- name: Get tasks from common and setup nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
- name: "copy {{component}} service file"
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
- name: Get tasks from common and setup nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql
- name: Deploy the latest code
  ansible.builtin.import_role:
    name: common
    tasks_from: deployment