- name: install mysql
  ansible.builtin.shell: dnf install mysql -y
- name: import data into mysql
  ansible.builtin.shell: "mysql -h {{login_host}} -uroot -p{{login_password}} < /app/schema/backend.sql"
- name: daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Enable backend service and start the service
  ansible.builtin.service:
    name: backend
    state: started
    enabled: yes